### ISSUE TITLE
missing module 

### ISSUE THREAD

**Issue by bhj02** [g2-bernotas/PS-Plant-Framework#5]
This is an interesting project. 
I am currently implementing your PSPP system in my lab but am stuck with a missing module.
When I run 'LeafSegmentationGUI.py', I get the following error message:

Traceback (most recent call last):
  File "C:\Users\bh-j\Desktop\PSPP\PS-Plant-Framework-dependabot-pip-tensorflow-gpu-1.15.2\LeafSegmentationGUI.py", line 37, in <module>
    from samples.GigaScience import LeafSegmentationConfig
ImportError: No module named 'samples'

Line 37 in 'LeafSementationGUI.py' is 
..............
37  from samples.GigaScience import LeafSegmentationConfig
..................
This module is needed in Line 150 of the same file.
...............
148   def process(self):
149       MODEL_DIR = os.path.join(MASK_DIR, "logs")
150      config = LeafSegmentationConfig.ArabidopsisLeafSegmentationConfig()
................

Seemingly, I am lack of the module named 'samples.GigaScience'. 
Could you please include the module or write some direction to fix it?

**Comment by g2-bernotas** [comment]
Hi @bhj02, thank you for your interest in my work. I am sorry, but it seems that the samples.GigaScience along with the MaskRCNN folder has been deleted from the Github possibly due to the tensorflow-gpu version. In any case, I have now added the missing MaskRCNN folder that has a samples subfolder and within it, you will find GigaScience sub-sub folder and LeafSegmentationConfig.py.
